/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AllEarningsSummary {
  'totalAppsWithPrices' : bigint,
  'totalValidEntries' : bigint,
  'appEarnings' : Array<AppEarnings>,
  'totalEarnings' : number,
}
export interface AppEarnings {
  'totalUsernamesFound' : bigint,
  'pricePerEntry' : number,
  'appName' : string,
  'isActive' : boolean,
  'totalAmount' : number,
}
export interface AppEvent { 'name' : string, 'usernames' : Array<string> }
export interface AppEventWithImportDate {
  'importDate' : [] | [string],
  'appEvent' : AppEvent,
}
export interface AppImport {
  'appName' : string,
  'importDate' : [] | [string],
  'usernames' : Array<string>,
}
export interface BulkCommentsResult {
  'commentListId' : string,
  'templateCount' : bigint,
  'generatedCount' : bigint,
  'comments' : Array<string>,
}
export interface ChatMessage {
  'id' : bigint,
  'text' : string,
  'timestamp' : Time,
}
export type ClaimCommentResult = { 'noCommentsRemaining' : null } |
  { 'claimSuccess' : string };
export interface CommentList {
  'id' : string,
  'templates' : Array<string>,
  'displayName' : string,
  'locked' : boolean,
  'suffix' : string,
}
export interface CountdownState {
  'isActive' : boolean,
  'targetTime' : [] | [Time],
}
export type ExternalBlob = Uint8Array;
export interface GlobalCommentPoolStats {
  'totalClaimed' : bigint,
  'totalTemplates' : bigint,
  'templatesRemaining' : bigint,
  'batchSupport' : boolean,
}
export interface ImageMeta {
  'id' : bigint,
  'dataUrl' : string,
  'data' : [] | [ExternalBlob],
  'name' : string,
  'tags' : Array<string>,
}
export interface ImportSummary {
  'totalUsernamesAdded' : bigint,
  'totalDuplicatesSkipped' : bigint,
  'totalAppsDetected' : bigint,
}
export interface ListMetrics {
  'usedTemplates' : bigint,
  'listName' : string,
  'availableTemplates' : bigint,
  'percentUsed' : number,
  'totalTemplates' : bigint,
  'listId' : string,
}
export interface PriceEntry {
  'pricePerEntry' : number,
  'appName' : string,
  'isActive' : boolean,
}
export interface PublicSettings {
  'bgMusicEnabled' : boolean,
  'musicFile' : [] | [ExternalBlob],
}
export interface Settings {
  'accessKey' : [] | [string],
  'bgMusicEnabled' : boolean,
  'musicFile' : [] | [ExternalBlob],
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WhatsAppSettings {
  'whatsAppLink' : string,
  'communityDescription' : string,
  'contactNumber' : string,
}
export interface WithdrawalRequest {
  'status' : WithdrawalStatus,
  'username' : string,
  'timestamp' : Time,
  'walletNumber' : string,
  'amount' : number,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatMessage' : ActorMethod<[string], ChatMessage>,
  'addGlobalComment' : ActorMethod<[string, string], undefined>,
  'addGlobalComments' : ActorMethod<[string, Array<string>], undefined>,
  'addPriceEntry' : ActorMethod<[string, string, number, boolean], undefined>,
  'addTemplatesToCommentList' : ActorMethod<
    [string, string, Array<string>],
    undefined
  >,
  'addUsernamesToAppEvent' : ActorMethod<
    [string, string, Array<string>],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUploadPrices' : ActorMethod<[string, Array<PriceEntry>], bigint>,
  'checkWithdrawalEligibility' : ActorMethod<[string], boolean>,
  'claimComment' : ActorMethod<[string, string], ClaimCommentResult>,
  'clearAccessKey' : ActorMethod<[string], undefined>,
  'clearCountdown' : ActorMethod<[string], undefined>,
  'clearMusicUrl' : ActorMethod<[string], undefined>,
  'consumeFromList' : ActorMethod<
    [string, bigint],
    { 'ok' : Array<string> } |
      { 'err' : string }
  >,
  'createAppEvent' : ActorMethod<[string, string], undefined>,
  'createCommentList' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'deleteAppEvent' : ActorMethod<[string, string], undefined>,
  'deleteChatMessage' : ActorMethod<[string, bigint], undefined>,
  'deleteCommentList' : ActorMethod<[string, string], undefined>,
  'deleteImage' : ActorMethod<[string, bigint], undefined>,
  'deletePriceEntry' : ActorMethod<[string, string], undefined>,
  'editPriceEntry' : ActorMethod<[string, string, number, boolean], undefined>,
  'generateBulk' : ActorMethod<
    [bigint],
    { 'ok' : Array<string> } |
      { 'err' : string }
  >,
  'generateSingle' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'getAllAppEvents' : ActorMethod<[], Array<AppEvent>>,
  'getAllAppEventsWithImportDate' : ActorMethod<
    [],
    Array<AppEventWithImportDate>
  >,
  'getAllChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getAllCommentLists' : ActorMethod<[], Array<CommentList>>,
  'getAllEarningsSummary' : ActorMethod<[string], AllEarningsSummary>,
  'getAllImages' : ActorMethod<[], Array<ImageMeta>>,
  'getAllInventory' : ActorMethod<[], Array<[string, bigint]>>,
  'getAllWithdrawalRequests' : ActorMethod<[string], Array<WithdrawalRequest>>,
  'getAppEvent' : ActorMethod<[string], [] | [AppEvent]>,
  'getAvailableCount' : ActorMethod<[string], bigint>,
  'getBulkComments' : ActorMethod<[string, string, bigint], BulkCommentsResult>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentList' : ActorMethod<[string], [] | [CommentList]>,
  'getCountdownState' : ActorMethod<[], CountdownState>,
  'getEarningsMode' : ActorMethod<[], string>,
  'getSingleCheckerEarningsEnabled' : ActorMethod<[], boolean>,
  'getBulkCheckerEarningsEnabled' : ActorMethod<[], boolean>,
  'getGlobalCommentPoolStats' : ActorMethod<[], GlobalCommentPoolStats>,
  'getImage' : ActorMethod<[bigint], [] | [ImageMeta]>,
  'getInventoryCount' : ActorMethod<[string], bigint>,
  'getListMetrics' : ActorMethod<[], Array<ListMetrics>>,
  'getMusicUrl' : ActorMethod<[], [] | [string]>,
  'getMyWithdrawalRequests' : ActorMethod<[string], Array<WithdrawalRequest>>,
  'getPerLinkRate' : ActorMethod<[], number>,
  'getPoolStats' : ActorMethod<
    [],
    { 'totalPoolSize' : bigint, 'availableCount' : bigint }
  >,
  'getPriceEntry' : ActorMethod<[string], [] | [PriceEntry]>,
  'getPriceList' : ActorMethod<[], Array<PriceEntry>>,
  'getPublicSettings' : ActorMethod<[], PublicSettings>,
  'getSettings' : ActorMethod<[string], Settings>,
  'getSpotifyUrl' : ActorMethod<[], [] | [string]>,
  'getWhatsAppSettings' : ActorMethod<[], WhatsAppSettings>,
  'importLiveLists' : ActorMethod<[string, Array<AppImport>], ImportSummary>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPriceListInitialized' : ActorMethod<[], boolean>,
  'lockCommentList' : ActorMethod<[string, string], undefined>,
  'regenerateAccessKey' : ActorMethod<[string], string>,
  'renameCommentList' : ActorMethod<[string, string, string], undefined>,
  'resetUsedTemplates' : ActorMethod<[string, string], undefined>,
  'setAccessKey' : ActorMethod<[string, string], undefined>,
  'setAdminCode' : ActorMethod<[string, string], boolean>,
  'setBgMusicEnabled' : ActorMethod<[string, boolean], undefined>,
  'setCommentListTemplates' : ActorMethod<
    [string, string, Array<string>],
    undefined
  >,
  'setCountdown' : ActorMethod<[string, Time], undefined>,
  'setEarningsMode' : ActorMethod<[string, string], undefined>,
  'setSingleCheckerEarningsEnabled' : ActorMethod<[string, boolean], undefined>,
  'setBulkCheckerEarningsEnabled' : ActorMethod<[string, boolean], undefined>,
  'setInventoryCount' : ActorMethod<[string, string, bigint], undefined>,
  'setMusicBlob' : ActorMethod<[string, ExternalBlob], undefined>,
  'setMusicUrl' : ActorMethod<[string, string], undefined>,
  'setPerLinkRate' : ActorMethod<[string, number], undefined>,
  'setPriceListInitialized' : ActorMethod<[string, boolean], undefined>,
  'setSpotifyUrl' : ActorMethod<[string, string], undefined>,
  'setWhatsAppSettings' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'stopCountdown' : ActorMethod<[string], undefined>,
  'submitWithdrawalRequest' : ActorMethod<
    [string, string, number],
    WithdrawalRequest
  >,
  'unlockCommentList' : ActorMethod<[string, string], undefined>,
  'updateImageTags' : ActorMethod<[string, bigint, Array<string>], undefined>,
  'updateSettings' : ActorMethod<[string, boolean, [] | [string]], undefined>,
  'updateWithdrawalStatus' : ActorMethod<
    [string, string, WithdrawalStatus],
    undefined
  >,
  'uploadImage' : ActorMethod<
    [string, string, Array<string>, string],
    ImageMeta
  >,
  'validateAccessKey' : ActorMethod<[string], boolean>,
  'verifyAdminCode' : ActorMethod<[string], boolean>,
  'wipeAllData' : ActorMethod<[string], undefined>,
  'wipeCompletedWithdrawals' : ActorMethod<[string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];