/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'timestamp' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PriceEntry = IDL.Record({
  'pricePerEntry' : IDL.Float64,
  'appName' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const ClaimCommentResult = IDL.Variant({
  'noCommentsRemaining' : IDL.Null,
  'claimSuccess' : IDL.Text,
});
export const AppEvent = IDL.Record({
  'name' : IDL.Text,
  'usernames' : IDL.Vec(IDL.Text),
});
export const AppEventWithImportDate = IDL.Record({
  'importDate' : IDL.Opt(IDL.Text),
  'appEvent' : AppEvent,
});
export const CommentList = IDL.Record({
  'id' : IDL.Text,
  'templates' : IDL.Vec(IDL.Text),
  'displayName' : IDL.Text,
  'locked' : IDL.Bool,
  'suffix' : IDL.Text,
});
export const AppEarnings = IDL.Record({
  'totalUsernamesFound' : IDL.Nat,
  'pricePerEntry' : IDL.Float64,
  'appName' : IDL.Text,
  'isActive' : IDL.Bool,
  'totalAmount' : IDL.Float64,
});
export const AllEarningsSummary = IDL.Record({
  'totalAppsWithPrices' : IDL.Nat,
  'totalValidEntries' : IDL.Nat,
  'appEarnings' : IDL.Vec(AppEarnings),
  'totalEarnings' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ImageMeta = IDL.Record({
  'id' : IDL.Nat,
  'dataUrl' : IDL.Text,
  'data' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'status' : WithdrawalStatus,
  'username' : IDL.Text,
  'timestamp' : Time,
  'walletNumber' : IDL.Text,
  'amount' : IDL.Float64,
});
export const BulkCommentsResult = IDL.Record({
  'commentListId' : IDL.Text,
  'templateCount' : IDL.Nat,
  'generatedCount' : IDL.Nat,
  'comments' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CountdownState = IDL.Record({
  'isActive' : IDL.Bool,
  'targetTime' : IDL.Opt(Time),
});
export const GlobalCommentPoolStats = IDL.Record({
  'totalClaimed' : IDL.Nat,
  'totalTemplates' : IDL.Nat,
  'templatesRemaining' : IDL.Nat,
  'batchSupport' : IDL.Bool,
});
export const ListMetrics = IDL.Record({
  'usedTemplates' : IDL.Nat,
  'listName' : IDL.Text,
  'availableTemplates' : IDL.Nat,
  'percentUsed' : IDL.Float64,
  'totalTemplates' : IDL.Nat,
  'listId' : IDL.Text,
});
export const PublicSettings = IDL.Record({
  'bgMusicEnabled' : IDL.Bool,
  'musicFile' : IDL.Opt(ExternalBlob),
});
export const Settings = IDL.Record({
  'accessKey' : IDL.Opt(IDL.Text),
  'bgMusicEnabled' : IDL.Bool,
  'musicFile' : IDL.Opt(ExternalBlob),
});
export const AppImport = IDL.Record({
  'appName' : IDL.Text,
  'importDate' : IDL.Opt(IDL.Text),
  'usernames' : IDL.Vec(IDL.Text),
});
export const ImportSummary = IDL.Record({
  'totalUsernamesAdded' : IDL.Nat,
  'totalDuplicatesSkipped' : IDL.Nat,
  'totalAppsDetected' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatMessage' : IDL.Func([IDL.Text], [ChatMessage], []),
  'addGlobalComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addGlobalComments' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'addPriceEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
      [],
      [],
    ),
  'addTemplatesToCommentList' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'addUsernamesToAppEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUploadPrices' : IDL.Func([IDL.Text, IDL.Vec(PriceEntry)], [IDL.Nat], []),
  'checkWithdrawalEligibility' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'claimComment' : IDL.Func([IDL.Text, IDL.Text], [ClaimCommentResult], []),
  'clearAccessKey' : IDL.Func([IDL.Text], [], []),
  'clearCountdown' : IDL.Func([IDL.Text], [], []),
  'consumeFromList' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
      [],
    ),
  'createAppEvent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createCommentList' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteAppEvent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteChatMessage' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteCommentList' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteImage' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deletePriceEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'editPriceEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
      [],
      [],
    ),
  'generateBulk' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
      [],
    ),
  'generateSingle' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getAllAppEvents' : IDL.Func([], [IDL.Vec(AppEvent)], ['query']),
  'getAllAppEventsWithImportDate' : IDL.Func(
      [],
      [IDL.Vec(AppEventWithImportDate)],
      ['query'],
    ),
  'getAllChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAllCommentLists' : IDL.Func([], [IDL.Vec(CommentList)], ['query']),
  'getAllEarningsSummary' : IDL.Func(
      [IDL.Text],
      [AllEarningsSummary],
      ['query'],
    ),
  'getAllImages' : IDL.Func([], [IDL.Vec(ImageMeta)], ['query']),
  'getAllInventory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAllWithdrawalRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getAppEvent' : IDL.Func([IDL.Text], [IDL.Opt(AppEvent)], ['query']),
  'getAvailableCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getBulkComments' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [BulkCommentsResult],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentList' : IDL.Func([IDL.Text], [IDL.Opt(CommentList)], ['query']),
  'getCountdownState' : IDL.Func([], [CountdownState], ['query']),
  'getGlobalCommentPoolStats' : IDL.Func(
      [],
      [GlobalCommentPoolStats],
      ['query'],
    ),
  'getImage' : IDL.Func([IDL.Nat], [IDL.Opt(ImageMeta)], ['query']),
  'getInventoryCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getListMetrics' : IDL.Func([], [IDL.Vec(ListMetrics)], ['query']),
  'getMusicUrl' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getSpotifyUrl' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getMyWithdrawalRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getPoolStats' : IDL.Func(
      [],
      [IDL.Record({ 'totalPoolSize' : IDL.Nat, 'availableCount' : IDL.Nat })],
      ['query'],
    ),
  'getPriceEntry' : IDL.Func([IDL.Text], [IDL.Opt(PriceEntry)], ['query']),
  'getPriceList' : IDL.Func([], [IDL.Vec(PriceEntry)], ['query']),
  'getPublicSettings' : IDL.Func([], [PublicSettings], ['query']),
  'getSettings' : IDL.Func([IDL.Text], [Settings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importLiveLists' : IDL.Func(
      [IDL.Text, IDL.Vec(AppImport)],
      [ImportSummary],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPriceListInitialized' : IDL.Func([], [IDL.Bool], ['query']),
  'lockCommentList' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'regenerateAccessKey' : IDL.Func([IDL.Text], [IDL.Text], []),
  'renameCommentList' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'resetUsedTemplates' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAccessKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setAdminCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setBgMusicEnabled' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setCommentListTemplates' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'setCountdown' : IDL.Func([IDL.Text, Time], [], []),
  'setInventoryCount' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'setMusicUrl' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setSpotifyUrl' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setPriceListInitialized' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'stopCountdown' : IDL.Func([IDL.Text], [], []),
  'submitWithdrawalRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [WithdrawalRequest],
      [],
    ),
  'unlockCommentList' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateImageTags' : IDL.Func([IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)], [], []),
  'updateSettings' : IDL.Func([IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)], [], []),
  'updateWithdrawalStatus' : IDL.Func(
      [IDL.Text, IDL.Text, WithdrawalStatus],
      [],
      [],
    ),
  'uploadImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [ImageMeta],
      [],
    ),
  'validateAccessKey' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'verifyAdminCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'wipeAllData' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'timestamp' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PriceEntry = IDL.Record({
    'pricePerEntry' : IDL.Float64,
    'appName' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const ClaimCommentResult = IDL.Variant({
    'noCommentsRemaining' : IDL.Null,
    'claimSuccess' : IDL.Text,
  });
  const AppEvent = IDL.Record({
    'name' : IDL.Text,
    'usernames' : IDL.Vec(IDL.Text),
  });
  const AppEventWithImportDate = IDL.Record({
    'importDate' : IDL.Opt(IDL.Text),
    'appEvent' : AppEvent,
  });
  const CommentList = IDL.Record({
    'id' : IDL.Text,
    'templates' : IDL.Vec(IDL.Text),
    'displayName' : IDL.Text,
    'locked' : IDL.Bool,
    'suffix' : IDL.Text,
  });
  const AppEarnings = IDL.Record({
    'totalUsernamesFound' : IDL.Nat,
    'pricePerEntry' : IDL.Float64,
    'appName' : IDL.Text,
    'isActive' : IDL.Bool,
    'totalAmount' : IDL.Float64,
  });
  const AllEarningsSummary = IDL.Record({
    'totalAppsWithPrices' : IDL.Nat,
    'totalValidEntries' : IDL.Nat,
    'appEarnings' : IDL.Vec(AppEarnings),
    'totalEarnings' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ImageMeta = IDL.Record({
    'id' : IDL.Nat,
    'dataUrl' : IDL.Text,
    'data' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'status' : WithdrawalStatus,
    'username' : IDL.Text,
    'timestamp' : Time,
    'walletNumber' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const BulkCommentsResult = IDL.Record({
    'commentListId' : IDL.Text,
    'templateCount' : IDL.Nat,
    'generatedCount' : IDL.Nat,
    'comments' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CountdownState = IDL.Record({
    'isActive' : IDL.Bool,
    'targetTime' : IDL.Opt(Time),
  });
  const GlobalCommentPoolStats = IDL.Record({
    'totalClaimed' : IDL.Nat,
    'totalTemplates' : IDL.Nat,
    'templatesRemaining' : IDL.Nat,
    'batchSupport' : IDL.Bool,
  });
  const ListMetrics = IDL.Record({
    'usedTemplates' : IDL.Nat,
    'listName' : IDL.Text,
    'availableTemplates' : IDL.Nat,
    'percentUsed' : IDL.Float64,
    'totalTemplates' : IDL.Nat,
    'listId' : IDL.Text,
  });
  const PublicSettings = IDL.Record({
    'bgMusicEnabled' : IDL.Bool,
    'musicFile' : IDL.Opt(ExternalBlob),
  });
  const Settings = IDL.Record({
    'accessKey' : IDL.Opt(IDL.Text),
    'bgMusicEnabled' : IDL.Bool,
    'musicFile' : IDL.Opt(ExternalBlob),
  });
  const AppImport = IDL.Record({
    'appName' : IDL.Text,
    'importDate' : IDL.Opt(IDL.Text),
    'usernames' : IDL.Vec(IDL.Text),
  });
  const ImportSummary = IDL.Record({
    'totalUsernamesAdded' : IDL.Nat,
    'totalDuplicatesSkipped' : IDL.Nat,
    'totalAppsDetected' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatMessage' : IDL.Func([IDL.Text], [ChatMessage], []),
    'addGlobalComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addGlobalComments' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'addPriceEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
        [],
        [],
      ),
    'addTemplatesToCommentList' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'addUsernamesToAppEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUploadPrices' : IDL.Func(
        [IDL.Text, IDL.Vec(PriceEntry)],
        [IDL.Nat],
        [],
      ),
    'checkWithdrawalEligibility' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'claimComment' : IDL.Func([IDL.Text, IDL.Text], [ClaimCommentResult], []),
    'clearAccessKey' : IDL.Func([IDL.Text], [], []),
    'clearCountdown' : IDL.Func([IDL.Text], [], []),
    'consumeFromList' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
        [],
      ),
    'createAppEvent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createCommentList' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteAppEvent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteChatMessage' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteCommentList' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteImage' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deletePriceEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'editPriceEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
        [],
        [],
      ),
    'generateBulk' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
        [],
      ),
    'generateSingle' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getAllAppEvents' : IDL.Func([], [IDL.Vec(AppEvent)], ['query']),
    'getAllAppEventsWithImportDate' : IDL.Func(
        [],
        [IDL.Vec(AppEventWithImportDate)],
        ['query'],
      ),
    'getAllChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAllCommentLists' : IDL.Func([], [IDL.Vec(CommentList)], ['query']),
    'getAllEarningsSummary' : IDL.Func(
        [IDL.Text],
        [AllEarningsSummary],
        ['query'],
      ),
    'getAllImages' : IDL.Func([], [IDL.Vec(ImageMeta)], ['query']),
    'getAllInventory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAllWithdrawalRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getAppEvent' : IDL.Func([IDL.Text], [IDL.Opt(AppEvent)], ['query']),
    'getAvailableCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getBulkComments' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [BulkCommentsResult],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentList' : IDL.Func([IDL.Text], [IDL.Opt(CommentList)], ['query']),
    'getCountdownState' : IDL.Func([], [CountdownState], ['query']),
    'getGlobalCommentPoolStats' : IDL.Func(
        [],
        [GlobalCommentPoolStats],
        ['query'],
      ),
    'getImage' : IDL.Func([IDL.Nat], [IDL.Opt(ImageMeta)], ['query']),
    'getInventoryCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getListMetrics' : IDL.Func([], [IDL.Vec(ListMetrics)], ['query']),
    'getMusicUrl' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getSpotifyUrl' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getMyWithdrawalRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getPoolStats' : IDL.Func(
        [],
        [IDL.Record({ 'totalPoolSize' : IDL.Nat, 'availableCount' : IDL.Nat })],
        ['query'],
      ),
    'getPriceEntry' : IDL.Func([IDL.Text], [IDL.Opt(PriceEntry)], ['query']),
    'getPriceList' : IDL.Func([], [IDL.Vec(PriceEntry)], ['query']),
    'getPublicSettings' : IDL.Func([], [PublicSettings], ['query']),
    'getSettings' : IDL.Func([IDL.Text], [Settings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importLiveLists' : IDL.Func(
        [IDL.Text, IDL.Vec(AppImport)],
        [ImportSummary],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPriceListInitialized' : IDL.Func([], [IDL.Bool], ['query']),
    'lockCommentList' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'regenerateAccessKey' : IDL.Func([IDL.Text], [IDL.Text], []),
    'renameCommentList' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'resetUsedTemplates' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAccessKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setAdminCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setBgMusicEnabled' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setCommentListTemplates' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'setCountdown' : IDL.Func([IDL.Text, Time], [], []),
    'setInventoryCount' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'setMusicUrl' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setSpotifyUrl' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setPriceListInitialized' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'stopCountdown' : IDL.Func([IDL.Text], [], []),
    'submitWithdrawalRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [WithdrawalRequest],
        [],
      ),
    'unlockCommentList' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateImageTags' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateSettings' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateWithdrawalStatus' : IDL.Func(
        [IDL.Text, IDL.Text, WithdrawalStatus],
        [],
        [],
      ),
    'uploadImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [ImageMeta],
        [],
      ),
    'validateAccessKey' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'verifyAdminCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'wipeAllData' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };