/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CommentAssignmentResponse = IDL.Record({
  'comment' : IDL.Text,
  'alreadyGenerated' : IDL.Bool,
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'timestamp' : Time,
});
export const Settings = IDL.Record({
  'accessKey' : IDL.Opt(IDL.Text),
  'bgMusicEnabled' : IDL.Bool,
  'musicFile' : IDL.Opt(ExternalBlob),
});
export const AppEvent = IDL.Record({
  'name' : IDL.Text,
  'usernames' : IDL.Vec(IDL.Text),
});
export const CommentList = IDL.Record({
  'id' : IDL.Text,
  'templates' : IDL.Vec(IDL.Text),
  'displayName' : IDL.Text,
  'locked' : IDL.Bool,
  'availableCount' : IDL.Nat,
  'suffix' : IDL.Text,
});
export const ImageMeta = IDL.Record({
  'id' : IDL.Nat,
  'dataUrl' : IDL.Text,
  'data' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
});
export const ExportData = IDL.Record({
  'chatMessages' : IDL.Vec(ChatMessage),
  'settings' : Settings,
  'appsEvents' : IDL.Vec(AppEvent),
  'commentLists' : IDL.Vec(CommentList),
  'images' : IDL.Vec(ImageMeta),
});
export const BulkCommentsResult = IDL.Record({
  'commentListId' : IDL.Text,
  'templateCount' : IDL.Nat,
  'generatedCount' : IDL.Nat,
  'comments' : IDL.Vec(IDL.Text),
});
export const OnePerListResult = IDL.Record({
  'listName' : IDL.Text,
  'comment' : IDL.Text,
  'listId' : IDL.Text,
});
export const ListMetrics = IDL.Record({
  'usedTemplates' : IDL.Nat,
  'listName' : IDL.Text,
  'availableTemplates' : IDL.Nat,
  'percentUsed' : IDL.Float64,
  'totalTemplates' : IDL.Nat,
  'listId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAppEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'addChatMessage' : IDL.Func([IDL.Text], [], []),
  'addCommentList' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'addImage' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'addTemplatesToList' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'addUsernamesToAppEvent' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'assignNextCommentFromList' : IDL.Func(
      [IDL.Text, IDL.Text],
      [CommentAssignmentResponse],
      [],
    ),
  'deleteAppEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteCommentList' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'editListName' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'exportAllData' : IDL.Func([], [ExportData], []),
  'generateBulkComments' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [BulkCommentsResult],
      [],
    ),
  'generateOnePerList' : IDL.Func([IDL.Text], [IDL.Vec(OnePerListResult)], []),
  'getAccessKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getAvailableCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getListMetrics' : IDL.Func([], [IDL.Vec(ListMetrics)], ['query']),
  'renameAppEvent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setAccessKey' : IDL.Func([IDL.Text], [], []),
  'toggleListLock' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateSettings' : IDL.Func([IDL.Bool, IDL.Opt(ExternalBlob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CommentAssignmentResponse = IDL.Record({
    'comment' : IDL.Text,
    'alreadyGenerated' : IDL.Bool,
  });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'timestamp' : Time,
  });
  const Settings = IDL.Record({
    'accessKey' : IDL.Opt(IDL.Text),
    'bgMusicEnabled' : IDL.Bool,
    'musicFile' : IDL.Opt(ExternalBlob),
  });
  const AppEvent = IDL.Record({
    'name' : IDL.Text,
    'usernames' : IDL.Vec(IDL.Text),
  });
  const CommentList = IDL.Record({
    'id' : IDL.Text,
    'templates' : IDL.Vec(IDL.Text),
    'displayName' : IDL.Text,
    'locked' : IDL.Bool,
    'availableCount' : IDL.Nat,
    'suffix' : IDL.Text,
  });
  const ImageMeta = IDL.Record({
    'id' : IDL.Nat,
    'dataUrl' : IDL.Text,
    'data' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
  });
  const ExportData = IDL.Record({
    'chatMessages' : IDL.Vec(ChatMessage),
    'settings' : Settings,
    'appsEvents' : IDL.Vec(AppEvent),
    'commentLists' : IDL.Vec(CommentList),
    'images' : IDL.Vec(ImageMeta),
  });
  const BulkCommentsResult = IDL.Record({
    'commentListId' : IDL.Text,
    'templateCount' : IDL.Nat,
    'generatedCount' : IDL.Nat,
    'comments' : IDL.Vec(IDL.Text),
  });
  const OnePerListResult = IDL.Record({
    'listName' : IDL.Text,
    'comment' : IDL.Text,
    'listId' : IDL.Text,
  });
  const ListMetrics = IDL.Record({
    'usedTemplates' : IDL.Nat,
    'listName' : IDL.Text,
    'availableTemplates' : IDL.Nat,
    'percentUsed' : IDL.Float64,
    'totalTemplates' : IDL.Nat,
    'listId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAppEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'addChatMessage' : IDL.Func([IDL.Text], [], []),
    'addCommentList' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'addImage' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'addTemplatesToList' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'addUsernamesToAppEvent' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'assignNextCommentFromList' : IDL.Func(
        [IDL.Text, IDL.Text],
        [CommentAssignmentResponse],
        [],
      ),
    'deleteAppEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteCommentList' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'editListName' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'exportAllData' : IDL.Func([], [ExportData], []),
    'generateBulkComments' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [BulkCommentsResult],
        [],
      ),
    'generateOnePerList' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OnePerListResult)],
        [],
      ),
    'getAccessKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getAvailableCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getListMetrics' : IDL.Func([], [IDL.Vec(ListMetrics)], ['query']),
    'renameAppEvent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setAccessKey' : IDL.Func([IDL.Text], [], []),
    'toggleListLock' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateSettings' : IDL.Func([IDL.Bool, IDL.Opt(ExternalBlob)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };