/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AllEarningsSummary {
  'totalAppsWithPrices' : bigint,
  'totalValidEntries' : bigint,
  'appEarnings' : Array<AppEarnings>,
  'totalEarnings' : number,
}
export interface AppEarnings {
  'totalUsernamesFound' : bigint,
  'pricePerEntry' : number,
  'appName' : string,
  'isActive' : boolean,
  'totalAmount' : number,
}
export interface AppEvent { 'name' : string, 'usernames' : Array<string> }
export interface AppEventWithImportDate {
  'importDate' : [] | [string],
  'appEvent' : AppEvent,
}
export interface AppImport {
  'appName' : string,
  'importDate' : [] | [string],
  'usernames' : Array<string>,
}
export interface BulkCommentsResult {
  'commentListId' : string,
  'templateCount' : bigint,
  'generatedCount' : bigint,
  'comments' : Array<string>,
}
export interface ChatMessage {
  'id' : bigint,
  'text' : string,
  'timestamp' : Time,
}
export type ClaimCommentResult = { 'noCommentsRemaining' : null } |
  { 'claimSuccess' : string };
export interface CommentList {
  'id' : string,
  'templates' : Array<string>,
  'displayName' : string,
  'locked' : boolean,
  'suffix' : string,
}
export interface CountdownState {
  'startedBy' : [] | [Principal],
  'isActive' : boolean,
  'targetTime' : [] | [Time],
}
export type ExternalBlob = Uint8Array;
export interface ImageMeta {
  'id' : bigint,
  'dataUrl' : string,
  'data' : [] | [ExternalBlob],
  'name' : string,
  'tags' : Array<string>,
}
export interface ImportSummary {
  'totalUsernamesAdded' : bigint,
  'totalDuplicatesSkipped' : bigint,
  'totalAppsDetected' : bigint,
}
export interface ListMetrics {
  'usedTemplates' : bigint,
  'listName' : string,
  'availableTemplates' : bigint,
  'percentUsed' : number,
  'totalTemplates' : bigint,
  'listId' : string,
}
export interface PriceEntry {
  'pricePerEntry' : number,
  'appName' : string,
  'isActive' : boolean,
}
export interface PublicSettings {
  'bgMusicEnabled' : boolean,
  'musicFile' : [] | [ExternalBlob],
}
export interface Settings {
  'accessKey' : [] | [string],
  'bgMusicEnabled' : boolean,
  'musicFile' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'status' : WithdrawalStatus,
  'username' : string,
  'timestamp' : Time,
  'walletNumber' : string,
  'amount' : number,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatMessage' : ActorMethod<[string], ChatMessage>,
  'addPriceEntry' : ActorMethod<[string, number, boolean], undefined>,
  'addTemplatesToCommentList' : ActorMethod<[string, Array<string>], undefined>,
  'addUsernamesToAppEvent' : ActorMethod<[string, Array<string>], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUploadPrices' : ActorMethod<[Array<PriceEntry>], bigint>,
  'checkWithdrawalEligibility' : ActorMethod<[string], boolean>,
  'claimComment' : ActorMethod<[string, string], ClaimCommentResult>,
  'clearAccessKey' : ActorMethod<[], undefined>,
  'clearCountdown' : ActorMethod<[], undefined>,
  'createAppEvent' : ActorMethod<[string], undefined>,
  'createCommentList' : ActorMethod<[string, string, string], undefined>,
  'deleteAppEvent' : ActorMethod<[string], undefined>,
  'deleteChatMessage' : ActorMethod<[bigint], undefined>,
  'deleteCommentList' : ActorMethod<[string], undefined>,
  'deleteImage' : ActorMethod<[bigint], undefined>,
  'deletePriceEntry' : ActorMethod<[string], undefined>,
  'editPriceEntry' : ActorMethod<[string, number, boolean], undefined>,
  'getAllAppEvents' : ActorMethod<[], Array<AppEvent>>,
  'getAllAppEventsWithImportDate' : ActorMethod<
    [],
    Array<AppEventWithImportDate>
  >,
  'getAllChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getAllCommentLists' : ActorMethod<[], Array<CommentList>>,
  'getAllEarningsSummary' : ActorMethod<[], AllEarningsSummary>,
  'getAllImages' : ActorMethod<[], Array<ImageMeta>>,
  'getAllInventory' : ActorMethod<[], Array<[string, bigint]>>,
  'getAllWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getAppEvent' : ActorMethod<[string], [] | [AppEvent]>,
  'getBulkComments' : ActorMethod<[string, bigint], BulkCommentsResult>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessage' : ActorMethod<[bigint], [] | [ChatMessage]>,
  'getCommentList' : ActorMethod<[string], [] | [CommentList]>,
  'getCountdownState' : ActorMethod<[], CountdownState>,
  'getImage' : ActorMethod<[bigint], [] | [ImageMeta]>,
  'getInventoryCount' : ActorMethod<[string], bigint>,
  'getListMetrics' : ActorMethod<[], Array<ListMetrics>>,
  'getMusicUrl' : ActorMethod<[], [] | [string]>,
  'getMyWithdrawalRequests' : ActorMethod<[string], Array<WithdrawalRequest>>,
  'getPriceEntry' : ActorMethod<[string], [] | [PriceEntry]>,
  'getPriceList' : ActorMethod<[], Array<PriceEntry>>,
  'getPublicSettings' : ActorMethod<[], PublicSettings>,
  'getSettings' : ActorMethod<[], Settings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importLiveLists' : ActorMethod<[Array<AppImport>], ImportSummary>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPriceListInitialized' : ActorMethod<[], boolean>,
  'lockCommentList' : ActorMethod<[string], undefined>,
  'regenerateAccessKey' : ActorMethod<[], string>,
  'renameCommentList' : ActorMethod<[string, string], undefined>,
  'resetUsedTemplates' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAccessKey' : ActorMethod<[string], undefined>,
  'setBgMusicEnabled' : ActorMethod<[boolean], undefined>,
  'setCommentListTemplates' : ActorMethod<[string, Array<string>], undefined>,
  'setCountdown' : ActorMethod<[Time], undefined>,
  'setInventoryCount' : ActorMethod<[string, bigint], undefined>,
  'setMusicUrl' : ActorMethod<[string], undefined>,
  'setPriceListInitialized' : ActorMethod<[boolean], undefined>,
  'stopCountdown' : ActorMethod<[], undefined>,
  'submitWithdrawalRequest' : ActorMethod<
    [string, string, number],
    WithdrawalRequest
  >,
  'unlockCommentList' : ActorMethod<[string], undefined>,
  'updateImageTags' : ActorMethod<[bigint, Array<string>], undefined>,
  'updateSettings' : ActorMethod<[boolean, [] | [string]], undefined>,
  'updateWithdrawalStatus' : ActorMethod<[string, WithdrawalStatus], undefined>,
  'uploadImage' : ActorMethod<[string, Array<string>, string], ImageMeta>,
  'validateAccessKey' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];