/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppEvent = IDL.Record({
  'name' : IDL.Text,
  'usernames' : IDL.Vec(IDL.Text),
});
export const CommentList = IDL.Record({
  'id' : IDL.Text,
  'templates' : IDL.Vec(IDL.Text),
  'displayName' : IDL.Text,
  'locked' : IDL.Bool,
  'suffix' : IDL.Text,
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'timestamp' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ImageMeta = IDL.Record({
  'id' : IDL.Nat,
  'dataUrl' : IDL.Text,
  'data' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'status' : WithdrawalStatus,
  'username' : IDL.Text,
  'timestamp' : Time,
  'walletNumber' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CountdownState = IDL.Record({
  'startedBy' : IDL.Opt(IDL.Principal),
  'isActive' : IDL.Bool,
  'targetTime' : IDL.Opt(Time),
});
export const ListMetrics = IDL.Record({
  'usedTemplates' : IDL.Nat,
  'listName' : IDL.Text,
  'availableTemplates' : IDL.Nat,
  'percentUsed' : IDL.Float64,
  'totalTemplates' : IDL.Nat,
  'listId' : IDL.Text,
});
export const PriceEntry = IDL.Record({
  'pricePerEntry' : IDL.Float64,
  'appName' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const PublicSettings = IDL.Record({
  'bgMusicEnabled' : IDL.Bool,
  'musicFile' : IDL.Opt(ExternalBlob),
});
export const Settings = IDL.Record({
  'accessKey' : IDL.Opt(IDL.Text),
  'bgMusicEnabled' : IDL.Bool,
  'musicFile' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAppEvent' : IDL.Func([IDL.Text, AppEvent], [], []),
  'createCommentList' : IDL.Func([CommentList], [], []),
  'getAllAppEvents' : IDL.Func([], [IDL.Vec(AppEvent)], ['query']),
  'getAllChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAllCommentLists' : IDL.Func([], [IDL.Vec(CommentList)], ['query']),
  'getAllImages' : IDL.Func([], [IDL.Vec(ImageMeta)], ['query']),
  'getAllInventory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getAppEvent' : IDL.Func([IDL.Text], [IDL.Opt(AppEvent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessage' : IDL.Func([IDL.Nat], [IDL.Opt(ChatMessage)], ['query']),
  'getCommentList' : IDL.Func([IDL.Text], [IDL.Opt(CommentList)], ['query']),
  'getCountdownState' : IDL.Func([], [CountdownState], ['query']),
  'getImage' : IDL.Func([IDL.Nat], [IDL.Opt(ImageMeta)], ['query']),
  'getInventoryCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getListMetrics' : IDL.Func([], [IDL.Vec(ListMetrics)], ['query']),
  'getPriceEntry' : IDL.Func([IDL.Text], [IDL.Opt(PriceEntry)], ['query']),
  'getPriceList' : IDL.Func([], [IDL.Vec(PriceEntry)], ['query']),
  'getPublicSettings' : IDL.Func([], [PublicSettings], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAccessKey' : IDL.Func([IDL.Text], [], []),
  'uploadMusicFile' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppEvent = IDL.Record({
    'name' : IDL.Text,
    'usernames' : IDL.Vec(IDL.Text),
  });
  const CommentList = IDL.Record({
    'id' : IDL.Text,
    'templates' : IDL.Vec(IDL.Text),
    'displayName' : IDL.Text,
    'locked' : IDL.Bool,
    'suffix' : IDL.Text,
  });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'timestamp' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ImageMeta = IDL.Record({
    'id' : IDL.Nat,
    'dataUrl' : IDL.Text,
    'data' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'status' : WithdrawalStatus,
    'username' : IDL.Text,
    'timestamp' : Time,
    'walletNumber' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CountdownState = IDL.Record({
    'startedBy' : IDL.Opt(IDL.Principal),
    'isActive' : IDL.Bool,
    'targetTime' : IDL.Opt(Time),
  });
  const ListMetrics = IDL.Record({
    'usedTemplates' : IDL.Nat,
    'listName' : IDL.Text,
    'availableTemplates' : IDL.Nat,
    'percentUsed' : IDL.Float64,
    'totalTemplates' : IDL.Nat,
    'listId' : IDL.Text,
  });
  const PriceEntry = IDL.Record({
    'pricePerEntry' : IDL.Float64,
    'appName' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const PublicSettings = IDL.Record({
    'bgMusicEnabled' : IDL.Bool,
    'musicFile' : IDL.Opt(ExternalBlob),
  });
  const Settings = IDL.Record({
    'accessKey' : IDL.Opt(IDL.Text),
    'bgMusicEnabled' : IDL.Bool,
    'musicFile' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAppEvent' : IDL.Func([IDL.Text, AppEvent], [], []),
    'createCommentList' : IDL.Func([CommentList], [], []),
    'getAllAppEvents' : IDL.Func([], [IDL.Vec(AppEvent)], ['query']),
    'getAllChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAllCommentLists' : IDL.Func([], [IDL.Vec(CommentList)], ['query']),
    'getAllImages' : IDL.Func([], [IDL.Vec(ImageMeta)], ['query']),
    'getAllInventory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getAppEvent' : IDL.Func([IDL.Text], [IDL.Opt(AppEvent)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessage' : IDL.Func([IDL.Nat], [IDL.Opt(ChatMessage)], ['query']),
    'getCommentList' : IDL.Func([IDL.Text], [IDL.Opt(CommentList)], ['query']),
    'getCountdownState' : IDL.Func([], [CountdownState], ['query']),
    'getImage' : IDL.Func([IDL.Nat], [IDL.Opt(ImageMeta)], ['query']),
    'getInventoryCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getListMetrics' : IDL.Func([], [IDL.Vec(ListMetrics)], ['query']),
    'getPriceEntry' : IDL.Func([IDL.Text], [IDL.Opt(PriceEntry)], ['query']),
    'getPriceList' : IDL.Func([], [IDL.Vec(PriceEntry)], ['query']),
    'getPublicSettings' : IDL.Func([], [PublicSettings], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAccessKey' : IDL.Func([IDL.Text], [], []),
    'uploadMusicFile' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };