/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppEvent { 'name' : string, 'usernames' : Array<string> }
export interface ChatMessage {
  'id' : bigint,
  'text' : string,
  'timestamp' : Time,
}
export interface CommentList {
  'id' : string,
  'templates' : Array<string>,
  'displayName' : string,
  'locked' : boolean,
  'suffix' : string,
}
export interface ExportData {
  'chatMessages' : Array<ChatMessage>,
  'settings' : Settings,
  'appsEvents' : Array<AppEvent>,
  'commentLists' : Array<CommentList>,
  'images' : Array<ImageMeta>,
}
export type ExternalBlob = Uint8Array;
export interface ImageMeta {
  'id' : bigint,
  'dataUrl' : string,
  'data' : [] | [ExternalBlob],
  'name' : string,
  'tags' : Array<string>,
}
export interface Settings {
  'accessKey' : [] | [string],
  'bgMusicEnabled' : boolean,
  'musicFile' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAppEvent' : ActorMethod<[string], boolean>,
  'addChatMessage' : ActorMethod<[string], undefined>,
  'addCommentList' : ActorMethod<[string, string, string], boolean>,
  'addImage' : ActorMethod<
    [string, Array<string>, string, [] | [ExternalBlob]],
    undefined
  >,
  'addTemplatesToList' : ActorMethod<[string, Array<string>], boolean>,
  'addUsernamesToAppEvent' : ActorMethod<[string, Array<string>], boolean>,
  'deleteAppEvent' : ActorMethod<[string], boolean>,
  'exportAllData' : ActorMethod<[], ExportData>,
  'getAccessKey' : ActorMethod<[], [] | [string]>,
  'renameAppEvent' : ActorMethod<[string, string], boolean>,
  'setAccessKey' : ActorMethod<[string], undefined>,
  'toggleListLock' : ActorMethod<[string], boolean>,
  'updateSettings' : ActorMethod<[boolean, [] | [ExternalBlob]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];