/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AllEarningsSummary {
  'totalAppsWithPrices' : bigint,
  'totalValidEntries' : bigint,
  'appEarnings' : Array<AppEarnings>,
  'totalEarnings' : number,
}
export interface AppEarnings {
  'totalUsernamesFound' : bigint,
  'pricePerEntry' : number,
  'appName' : string,
  'isActive' : boolean,
  'totalAmount' : number,
}
export interface AppEvent { 'name' : string, 'usernames' : Array<string> }
export interface AppImport {
  'appName' : string,
  'importDate' : [] | [string],
  'usernames' : Array<string>,
}
export interface BulkCommentsResult {
  'commentListId' : string,
  'templateCount' : bigint,
  'generatedCount' : bigint,
  'comments' : Array<string>,
}
export interface ChatMessage {
  'id' : bigint,
  'text' : string,
  'timestamp' : Time,
}
export type ClaimCommentResult = { 'noCommentsRemaining' : null } |
  { 'claimSuccess' : string };
export interface CommentList {
  'id' : string,
  'templates' : Array<string>,
  'displayName' : string,
  'locked' : boolean,
  'suffix' : string,
}
export interface CountdownState {
  'startedBy' : [] | [Principal],
  'isActive' : boolean,
  'targetTime' : [] | [Time],
}
export interface ExportData {
  'chatMessages' : Array<ChatMessage>,
  'settings' : Settings,
  'appsEvents' : Array<AppEvent>,
  'commentLists' : Array<CommentList>,
  'images' : Array<ImageMeta>,
}
export type ExternalBlob = Uint8Array;
export interface ImageMeta {
  'id' : bigint,
  'dataUrl' : string,
  'data' : [] | [ExternalBlob],
  'name' : string,
  'tags' : Array<string>,
}
export interface ImportSummary {
  'totalUsernamesAdded' : bigint,
  'totalDuplicatesSkipped' : bigint,
  'totalAppsDetected' : bigint,
}
export interface ListMetrics {
  'usedTemplates' : bigint,
  'listName' : string,
  'availableTemplates' : bigint,
  'percentUsed' : number,
  'totalTemplates' : bigint,
  'listId' : string,
}
export interface PriceEntry {
  'pricePerEntry' : number,
  'appName' : string,
  'isActive' : boolean,
}
export interface PublicSettings {
  'bgMusicEnabled' : boolean,
  'musicFile' : [] | [ExternalBlob],
}
export interface Settings {
  'accessKey' : [] | [string],
  'bgMusicEnabled' : boolean,
  'musicFile' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'status' : WithdrawalStatus,
  'username' : string,
  'timestamp' : Time,
  'walletNumber' : string,
  'amount' : number,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAppEvent' : ActorMethod<[string], boolean>,
  'addChatMessage' : ActorMethod<[string], undefined>,
  'addCommentList' : ActorMethod<[string, string, string], boolean>,
  'addImage' : ActorMethod<
    [string, Array<string>, string, [] | [ExternalBlob]],
    undefined
  >,
  'addTemplatesToList' : ActorMethod<[string, Array<string>], boolean>,
  'addUsernamesToAppEvent' : ActorMethod<[string, Array<string>], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkSetPrices' : ActorMethod<[Array<[string, number, boolean]>], undefined>,
  'calculateAllEarnings' : ActorMethod<[], AllEarningsSummary>,
  'calculateEarnings' : ActorMethod<[string], [] | [AppEarnings]>,
  'checkAndRequestWithdrawal' : ActorMethod<[string, string], [] | [number]>,
  'claimComment' : ActorMethod<[string], ClaimCommentResult>,
  'deleteAppEvent' : ActorMethod<[string], boolean>,
  'deleteCommentList' : ActorMethod<[string], boolean>,
  'deletePriceEntry' : ActorMethod<[string], undefined>,
  'exportAllData' : ActorMethod<[], [] | [ExportData]>,
  'generateBulkComments' : ActorMethod<[string, bigint], BulkCommentsResult>,
  'getAccessKey' : ActorMethod<[], [] | [string]>,
  'getAllInventory' : ActorMethod<[], Array<[string, bigint]>>,
  'getAllWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getAvailableComments' : ActorMethod<
    [string],
    { 'count' : bigint, 'comments' : Array<string> }
  >,
  'getAvailableCount' : ActorMethod<[string], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentListsOrder' : ActorMethod<[], Array<string>>,
  'getCountdownState' : ActorMethod<[], CountdownState>,
  'getInventoryCount' : ActorMethod<[string], bigint>,
  'getListMetrics' : ActorMethod<[], Array<ListMetrics>>,
  'getPriceList' : ActorMethod<[], Array<PriceEntry>>,
  'getPublicSettings' : ActorMethod<[], PublicSettings>,
  'getSettings' : ActorMethod<[], Settings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importLiveList' : ActorMethod<[Array<AppImport>], ImportSummary>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'pauseCountdown' : ActorMethod<[], undefined>,
  'renameAppEvent' : ActorMethod<[string, string], boolean>,
  'renameCommentList' : ActorMethod<[string, string, string], boolean>,
  'resetCountdown' : ActorMethod<[], undefined>,
  'resumeCountdown' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAccessKey' : ActorMethod<[string], undefined>,
  'setCountdown' : ActorMethod<[Time], undefined>,
  'setInventoryCount' : ActorMethod<[string, bigint], undefined>,
  'setPriceEntry' : ActorMethod<[string, number, boolean], undefined>,
  'toggleListLock' : ActorMethod<[string], boolean>,
  'updateInventory' : ActorMethod<[string, bigint], boolean>,
  'updateSettings' : ActorMethod<[boolean, [] | [ExternalBlob]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];